# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Graft < Formula
  desc "Agentless deployment tool extending Docker Compose to cloud via SSH"
  homepage "https://github.com/skssmd/graft"
  version "2.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skssmd/Graft/releases/download/v2.2.3/Graft_2.2.3_Darwin_amd64.tar.gz"
      sha256 "b68848c8370a3cdfa66a3a22d308d8079e96cbf2dc646242dbb3604e684cbcb8"

      def install
        bin.install "graft"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skssmd/Graft/releases/download/v2.2.3/Graft_2.2.3_Darwin_arm64.tar.gz"
      sha256 "2cca57d299572a389110d7f69544960a7d6897f87f243273fc1bdc52b5b4c7af"

      def install
        bin.install "graft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skssmd/Graft/releases/download/v2.2.3/Graft_2.2.3_Linux_amd64.tar.gz"
      sha256 "6b233490fa05608c59375df48ae2198f83f4616bed15b1b2a592fa836e9ca07b"
      def install
        bin.install "graft"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skssmd/Graft/releases/download/v2.2.3/Graft_2.2.3_Linux_arm64.tar.gz"
      sha256 "9a78142e01b0a9dfbb36c433aacae6f8785f435b0652b788c29986875002d8bb"
      def install
        bin.install "graft"
      end
    end
  end

  test do
    system "#{bin}/graft --version"
  end
end
