# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Graft < Formula
  desc "A simple agentless deployment engine that extends the Docker Compose workflow to cloud infrastructure via SSH. Graft enables native remote management of AWS, GCP, and VPS instances with no agent installs or server-side overhead required. With features like DNS Configurations, Rollbacks, CI/CD Workflow"
  homepage "https://github.com/skssmd/graft"
  version "2.2.2-beta.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skssmd/Graft/releases/download/v2.2.2-beta.4/Graft_2.2.2-beta.4_Darwin_amd64.tar.gz"
      sha256 "1360dcb4d4c2a551613275b91cc85a6baa6095a92eea8161bb7752f961ffe371"

      def install
        bin.install "graft"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skssmd/Graft/releases/download/v2.2.2-beta.4/Graft_2.2.2-beta.4_Darwin_arm64.tar.gz"
      sha256 "c8bc5d283266b91e01f7a96f3c6e5b3a8b4a0a98c31b209d8737c4eeadabd9da"

      def install
        bin.install "graft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skssmd/Graft/releases/download/v2.2.2-beta.4/Graft_2.2.2-beta.4_Linux_amd64.tar.gz"
      sha256 "cd68bf57affdf1de28ecb22617018b7f925a5ea4df5ddd6967462ad78e922415"
      def install
        bin.install "graft"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skssmd/Graft/releases/download/v2.2.2-beta.4/Graft_2.2.2-beta.4_Linux_arm64.tar.gz"
      sha256 "b3dd211ee5dd911d6816d7550840736564a69d2102e344713bda74b0d90dd566"
      def install
        bin.install "graft"
      end
    end
  end

  test do
    system "#{bin}/graft --version"
  end
end
