# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Graft < Formula
  desc "Agentless deployment tool extending Docker Compose to cloud via SSH"
  homepage "https://github.com/skssmd/graft"
  version "2.2.2-beta.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skssmd/Graft/releases/download/v2.2.2-beta.6/Graft_2.2.2-beta.6_Darwin_amd64.tar.gz"
      sha256 "8e0b4fcf083d9eeb57e2a98e6126f48d129eb5190dd29bf95d0244db33ec97ba"

      def install
        bin.install "graft"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skssmd/Graft/releases/download/v2.2.2-beta.6/Graft_2.2.2-beta.6_Darwin_arm64.tar.gz"
      sha256 "31247e65a79f98709968515cc7463eb834c2511e7f5f34721ca1bbf85498ebab"

      def install
        bin.install "graft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skssmd/Graft/releases/download/v2.2.2-beta.6/Graft_2.2.2-beta.6_Linux_amd64.tar.gz"
      sha256 "d03e739de1fe859556ac35e9717b08eb9bddd884858848c0899c2e78314fbd7a"
      def install
        bin.install "graft"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skssmd/Graft/releases/download/v2.2.2-beta.6/Graft_2.2.2-beta.6_Linux_arm64.tar.gz"
      sha256 "5d1039ad986dd205033e6ea39252d636a578c35a613babaae23d9754d148807c"
      def install
        bin.install "graft"
      end
    end
  end

  test do
    system "#{bin}/graft --version"
  end
end
