# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Graft < Formula
  desc "Agentless deployment tool extending Docker Compose to cloud via SSH"
  homepage "https://github.com/skssmd/graft"
  version "2.2.2-beta.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skssmd/Graft/releases/download/v2.2.2-beta.9/Graft_2.2.2-beta.9_Darwin_amd64.tar.gz"
      sha256 "f57108da7d64376252e511c7eb9830ebe728c21b62473c16b70b5489492824c4"

      def install
        bin.install "graft"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skssmd/Graft/releases/download/v2.2.2-beta.9/Graft_2.2.2-beta.9_Darwin_arm64.tar.gz"
      sha256 "56b58af07f66f1f9fc90ff71650b3effc7f8550feb602dd6d4b07e249a33413b"

      def install
        bin.install "graft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skssmd/Graft/releases/download/v2.2.2-beta.9/Graft_2.2.2-beta.9_Linux_amd64.tar.gz"
      sha256 "e301a8820ededc7fd12843b8267c31c96446a172a3968f5806079bc49646e5fb"
      def install
        bin.install "graft"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skssmd/Graft/releases/download/v2.2.2-beta.9/Graft_2.2.2-beta.9_Linux_arm64.tar.gz"
      sha256 "2cd31e4d59c106b53c9a12e79ae32097b8ea996474164cfadbf529789f2ebf9f"
      def install
        bin.install "graft"
      end
    end
  end

  test do
    system "#{bin}/graft --version"
  end
end
