# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Graft < Formula
  desc "Agentless deployment tool extending Docker Compose to cloud via SSH"
  homepage "https://github.com/skssmd/graft"
  version "2.2.2-beta.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/skssmd/Graft/releases/download/v2.2.2-beta.5/Graft_2.2.2-beta.5_Darwin_amd64.tar.gz"
      sha256 "90a3dae862d270c772c65bd8803bee4be5e06825fcf4fe41c93308664f74db37"

      def install
        bin.install "graft"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/skssmd/Graft/releases/download/v2.2.2-beta.5/Graft_2.2.2-beta.5_Darwin_arm64.tar.gz"
      sha256 "2aa4e526f2c6a0a632b9c1534b646658b7e89890a3a1b98a591fe77b2f41bfe4"

      def install
        bin.install "graft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/skssmd/Graft/releases/download/v2.2.2-beta.5/Graft_2.2.2-beta.5_Linux_amd64.tar.gz"
      sha256 "7655b18efb6f05c62663d349eaf1908ed5339b6090e03d43ab48ef19ff02339e"
      def install
        bin.install "graft"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/skssmd/Graft/releases/download/v2.2.2-beta.5/Graft_2.2.2-beta.5_Linux_arm64.tar.gz"
      sha256 "dfc768b06a7c379a7a9e13021bca6d8e70adf9ecdc874b49b5946f8ae9f35ecc"
      def install
        bin.install "graft"
      end
    end
  end

  test do
    system "#{bin}/graft --version"
  end
end
